---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: PRE_TASK | Install python3
      changed_when: false
      ansible.builtin.raw: |-
        sh -ec '
          command -v python3 >/dev/null 2>&1 && exit 0
          if command -v apt >/dev/null 2>&1; then
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt -y --no-install-recommends install python3
          elif command -v dnf >/dev/null 2>&1; then
            dnf makecache
            dnf -y install python3
          elif command -v yum >/dev/null 2>&1; then
            yum makecache
            yum -y install python3
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache python3
          fi
        '
    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - role: ansible-role-motd
