---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    tmpfs:
      /run: "rw"
      /tmp: "rw"
# Required for 'offline' role testing
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"
verifier:
  name: ansible
